### ISSUE TITLE
Open API schema type errors

### ISSUE THREAD

**Issue by joshpostel** [part-os/core-python#40]
The website's [`openapi.json`](https://docs.paperlessparts.com/static/media/openapi.39750856b208ece6e09d.yaml) appears to have some incorrect types.  For example `payment_terms_period` has type `string` in some places, when it appears to be an `integer`.

```yaml
    post:
      summary: Create new Account
...
                payment_terms_period:
                  type: string
                  nullable: true
                  description: Payment terms period in days; required if `payment_terms` are included, but can be `null`
                  example: 30
```

```yaml
    OrderContact:
  ...
            payment_terms_period:
              type: string
              nullable: true
```

```yaml
    Account:
...
        payment_terms_period:
          type: integer
          nullable: true
          example: 30
```

This leads to deserialization errors in some openapi clients:
```
config: Configuration { base_path: "https://api.paperlessparts.com", user_agent: Some("OpenAPI-Generator/1.0/rust"), client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"} }, basic_auth: None, oauth_access_token: None, bearer_access_token: None, api_key: Some(ApiKey { prefix: Some("API-Token"), key: "xxx" }) }
resp: Err(Serde(Error("invalid type: integer `30`, expected a string", line: 1, column: 621)))

```
